tasks:
  - init: npm install
    command: |
      gp await-port 8000
      dfx canister create --all
      dfx build
      dfx canister install --all
      ID=$(dfx canister id logo_assets)
      gp preview $(gp url 8000)/?canisterId=ic:$ID
  - command: dfx start --clean
    name: replica
    openMode: tab-after
image:
  file: .gitpod.Dockerfile
ports:
  - port: 8000
    onOpen: ignore
vscode:
  extensions:
    - dfinity-foundation.vscode-motoko@0.3.4:94sM6KNSH0sWMuF40BrlUQ==
