dist: bionic
env:
- DFX_VERSION="0.5.4"
install:
- travis_retry wget https://deb.nodesource.com/setup_12.x -O /tmp/install-node.sh
- sudo sh /tmp/install-node.sh
- travis_retry sudo apt-get install -y nodejs
- travis_retry wget https://sdk.dfinity.org/install.sh -O /tmp/install-sdk.sh
- sh -c 'yes Y | sh /tmp/install-sdk.sh'
- export PATH=/home/$USER/bin:$PATH
- npm install
script:
- dfx build
