name: "build"
on: pull_request
jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "install dfx"
      run: |
        wget https://sdk.dfinity.org/install.sh
        yes Y | DFX_VERSION=0.6.2 sh install.sh
        echo "::add-path::/home/runner/bin"
    - name: "build"
      run: |
        dfx start --background
        dfx canister create --all
        dfx build
        dfx canister install --all
